In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import pandas as pd

In [2]:
data = load_iris()
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [3]:
X = df.drop('target', axis=1)
y = df['target']

In [4]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.05, random_state=42)
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [5]:
y_pred = knn.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 1.00

In [6]:
# lets copy the X_test
x_test_copy = x_test.copy()
x_test_copy['predicted_target'] = y_pred
x_test_copy['actual_target'] = y_test.values

x_test_copy.head(2)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),predicted_target,actual_target
73,6.1,2.8,4.7,1.2,1,1
18,5.7,3.8,1.7,0.3,0,0

In [7]:
import pandas as pd
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [20]:
# lets create imbalanced dataset
X, y = make_classification(n_samples=1000, n_features=50, n_informative=2, 
                           n_redundant=10, n_clusters_per_class=1, weights=[0.90, 0.10], flip_y=0, random_state=42)
#n_redundant = 10 # here we define number of redundant features : why because we want to create imbalanced dataset
df = pd.DataFrame(X, columns=[f'feature_{i}' for i in range(X.shape[1])])
df['target'] = y
df.head(2)

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,...,feature_41,feature_42,feature_43,feature_44,feature_45,feature_46,feature_47,feature_48,feature_49,target
0,0.729370,-0.113597,-0.267839,-1.010997,1.168769,0.010693,1.093758,1.653774,-0.705985,0.738717,...,0.937483,2.127297,0.661733,0.853060,-2.553631,-0.372095,1.896604,-0.896587,-0.405737,0
1,-0.590043,-1.175880,0.784558,0.498639,-0.113572,0.637160,-0.332000,1.130410,-0.743084,0.620619,...,-0.286972,0.525914,1.534292,0.549022,-1.602769,0.487645,0.302323,-0.864043,-0.229716,0

In [9]:
# split the data
X = df.drop('target', axis=1)
y = df['target']
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train, y_train)

y_pred = knn.predict(x_test)
# checking accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy on imbalanced dataset: {accuracy:.2f}")

Accuracy on imbalanced dataset: 0.95

In [10]:
# copy of x_test
x_test_copy = x_test.copy()
x_test_copy['predicted_target'] = y_pred
x_test_copy['actual_target'] = y_test.values
# filter where predicted target is 1 but actual target is 0
x_test_copy[(x_test_copy['predicted_target'] == 0) & (x_test_copy['actual_target'] == 1)]

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,predicted_target,actual_target
101,-1.514298,-0.939463,1.119245,2.718983,-0.294456,-0.901433,-0.527723,-1.306380,-2.626801,0.359523,0,1
902,-1.279317,-0.262747,-1.595894,2.423189,-0.739029,-0.849363,-0.470410,-1.196603,-2.274952,0.242324,0,1
221,-0.692609,-1.120047,0.670911,3.256446,0.603791,-1.813673,-0.633594,-2.080758,-2.091408,-0.815615,0,1
209,-1.057059,-0.114641,0.264268,2.179591,-0.150117,-0.825302,-0.423251,-1.119430,-1.958151,0.113854,0,1
382,-0.920439,-0.978500,2.755218,1.711181,-0.305611,-0.588646,-0.332165,-0.837165,-1.622517,0.190047,0,1
959,-0.915856,-0.385673,0.434503,1.871766,0.240206,-0.703449,-0.363464,-0.957609,-1.689207,0.106764,0,1
995,-1.416963,1.202451,-1.095271,1.557469,-3.176704,-0.156501,-0.301524,-0.495284,-2.021674,0.816861,0,1
254,-0.802641,0.756488,-1.914060,1.488194,0.659451,-0.510533,-0.288877,-0.727085,-1.413104,0.167668,0,1
845,-1.078296,0.652330,1.427305,2.853691,-0.419435,-1.280717,-0.554577,-1.606391,-2.276180,-0.190756,0,1

In [11]:
# pass new input to the model
input = [[0.5]*10]
prediction = knn.predict(input)
print(f"Prediction for input {input}: {prediction}")

Prediction for input [[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]]: [0]

/Users/rahultiwari/Documents/ml_akila/ml-env/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

In [12]:
# lets check the shape x_train and y_train
print(f"x_train shape: {X.shape}, y_train shape: {y.shape}")

x_train shape: (1000, 10), y_train shape: (1000,)

In [13]:
y.value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [14]:
# oversampling the minority class using SMOTE
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)
print(f"Resampled X shape: {X_resampled.shape}, Resampled y shape: {y_resampled.shape}")

Resampled X shape: (1800, 10), Resampled y shape: (1800,)

In [15]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_resampled, y_resampled)   
y_pred = knn.predict(x_test)
# checking accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy after SMOTE: {accuracy:.2f}")

Accuracy after SMOTE: 0.98

In [16]:
# undersampling the majority class using RandomUnderSampler
from imblearn.under_sampling import RandomUnderSampler
rus = RandomUnderSampler(random_state=42)
X_resampled, y_resampled = rus.fit_resample(X, y)

### Assignment

In [17]:


# Read official documentation for KNN: https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html
# Do some experiment with different parameters of KNN and observe the changes in accuracy.( library one only : iris dataset)
# Try to create imbalanced dataset and see how KNN is performing.
# Try to use oversampling and undersampling techniques to balance the dataset and see how KNN is performing.
# Try to read ateast one blog for KNN (https://medium.com/swlh/k-nearest-neighbor-ca2593d7a3c4)

In [18]:
# https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html#sklearn.neighbors.KNeighborsClassifier

In [19]:
# Implement KNN from scratch : not using any library functions : load_iris()

In [21]:
X, y = make_classification(n_samples=1000, n_features=50, n_informative=2, 
                           n_redundant=10, n_clusters_per_class=1, weights=[0.90, 0.10], flip_y=0, random_state=42)
#n_redundant = 10 # here we define number of redundant features : why because we want to create imbalanced dataset
df = pd.DataFrame(X, columns=[f'feature_{i}' for i in range(X.shape[1])])
df['target'] = y
df.head(2)

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,...,feature_41,feature_42,feature_43,feature_44,feature_45,feature_46,feature_47,feature_48,feature_49,target
0,0.729370,-0.113597,-0.267839,-1.010997,1.168769,0.010693,1.093758,1.653774,-0.705985,0.738717,...,0.937483,2.127297,0.661733,0.853060,-2.553631,-0.372095,1.896604,-0.896587,-0.405737,0
1,-0.590043,-1.175880,0.784558,0.498639,-0.113572,0.637160,-0.332000,1.130410,-0.743084,0.620619,...,-0.286972,0.525914,1.534292,0.549022,-1.602769,0.487645,0.302323,-0.864043,-0.229716,0

In [ ]:
# use RFE to select top 10 features
from sklearn.feature_selection import RFE #https://scikit-learn.org/stable/modules/feature_selection.html
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
rfe = RFE(estimator=log_reg, n_features_to_select=10)
rfe.fit(X, y)

X_rfe = rfe.transform(X)
X_rfe.shape

# RFE will only work with model which have coef_ or feature_importances_ attribute
# what to do with KNN ? 

# manually select top 10 features based on domain knowledge or correlation analysis
# Q) Can we apply RFE with KNN ?
# Ans ) No, because KNN does not have coef_ or feature_importances_ attribute. and this also proof 
# that KNN is not interpretable model.
# yes we can use other feature selection techniques like PCA, mutual_info_classif etc.
# or use manual feature selection based on domain knowledge.  + correlation analysis.

(1000, 10)

In [7]:
# Explore model based imputation to fill missing values in dataset.
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
data = {'feature_1': [1, 2, None, 4, 5],
        'feature_2': [5, None, None, 8, 10],
        'target': [0, 1, 0, 1, 0]}

df = pd.DataFrame(data)
df.head()

   feature_1  feature_2  target
0        1.0        5.0       0
1        2.0        NaN       1
2        NaN        NaN       0
3        4.0        8.0       1
4        5.0       10.0       0

In [9]:
# you can use mean impurtation for numerical features
df['feature_1'].fillna(df['feature_1'].mean(), inplace=True)
df['feature_2'].fillna(df['feature_2'].mean(), inplace=True)
df.head()

/var/folders/fq/kr6gv5l17pd4j572n0_n3f2c0000gn/T/ipykernel_54109/4194580022.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['feature_1'].fillna(df['feature_1'].mean(), inplace=True)
/var/folders/fq/kr6gv5l17pd4j572n0_n3f2c0000gn/T/ipykernel_54109/4194580022.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['feature_2'].fillna(df['feature_2'].mean(), inplace=True)

   feature_1  feature_2  target
0        1.0   5.000000       0
1        2.0   7.666667       1
2        3.0   7.666667       0
3        4.0   8.000000       1
4        5.0  10.000000       0

In [10]:
knn = KNeighborsClassifier(n_neighbors=3)
X_train = df[['feature_1', 'feature_2']]
y_train = df.loc[X_train.index, 'target']
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
# Refer below blog for more details on bias-variance tradeoff.
# https://medium.com/30-days-of-machine-learning/day-3-k-nearest-neighbors-and-bias-variance-tradeoff-75f84d515bdb

In [7]:
import pandas as pd

data = {
    'product_category': ['Electronics', 'Clothing', 'Home', 'Books', 'Toys'],
    'price': [299.99, 49.99, 89.99, 19.99, 24.99],
    'rating': [4.5, 4.0, 4.8, 4.2, 4.6]
}

df = pd.DataFrame(data)
df.head()

  product_category   price  rating
0      Electronics  299.99     4.5
1         Clothing   49.99     4.0
2             Home   89.99     4.8
3            Books   19.99     4.2
4             Toys   24.99     4.6

In [8]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder()
encoded_features = encoder.fit_transform(df[['product_category']])
encoded_features_df = pd.DataFrame(encoded_features.toarray(), columns=encoder.get_feature_names_out())
df = pd.concat([df, encoded_features_df], axis=1)
df.drop('product_category', axis=1, inplace=True)

# save encoder model
import pickle

with open('encoder.pkl', 'wb') as f:
    pickle.dump(encoder, f)

In [10]:
# new data
import numpy as np
new_data = np.array([['Rahul', 299.99, 4.5]])
# load the 

with open('encoder.pkl', 'rb') as f:
    encoder = pickle.load(f)

encoder.transform(new_data[:, [0]])

/Users/rahultiwari/Documents/ml_akila/ml-env/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

ValueError: Found unknown categories [np.str_('Rahul')] in column 0 during transform