In [3]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import pandas as pd

In [4]:
data = load_iris()
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target
df.head()

   sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
0                5.1               3.5  ...               0.2       0
1                4.9               3.0  ...               0.2       0
2                4.7               3.2  ...               0.2       0
3                4.6               3.1  ...               0.2       0
4                5.0               3.6  ...               0.2       0

[5 rows x 5 columns]

In [5]:
X = df.drop('target', axis=1)
y = df['target']

In [6]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.05, random_state=42)
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [7]:
y_pred = knn.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 1.00

In [8]:
# lets copy the X_test
x_test_copy = x_test.copy()
x_test_copy['predicted_target'] = y_pred
x_test_copy['actual_target'] = y_test.values

x_test_copy.head(2)

    sepal length (cm)  sepal width (cm)  ...  predicted_target  actual_target
73                6.1               2.8  ...                 1              1
18                5.7               3.8  ...                 0              0

[2 rows x 6 columns]

In [7]:
import pandas as pd
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [18]:
# lets create imbalanced dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=2, 
                           n_redundant=5, n_clusters_per_class=1, weights=[0.90, 0.10], flip_y=0, random_state=42)
#n_redundant = 10 # here we define number of redundant features : why because we want to create imbalanced dataset
df = pd.DataFrame(X, columns=[f'feature_{i}' for i in range(X.shape[1])])
df['target'] = y
df.head(2)

   feature_0  feature_1  feature_2  ...  feature_8  feature_9  target
0  -2.232426   0.957840  -0.790882  ...  -1.803823    2.80812       1
1   1.546688   1.533434  -1.423957  ...   1.463670   -1.70996       0

[2 rows x 11 columns]

In [19]:
# split the data
X = df.drop('target', axis=1)
y = df['target']
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train, y_train)

y_pred = knn.predict(x_test)
# checking accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy on imbalanced dataset: {accuracy:.2f}")

Accuracy on imbalanced dataset: 0.95

In [20]:
# copy of x_test
x_test_copy = x_test.copy()
x_test_copy['predicted_target'] = y_pred
x_test_copy['actual_target'] = y_test.values
# filter where predicted target is 1 but actual target is 0
x_test_copy[(x_test_copy['predicted_target'] == 0) & (x_test_copy['actual_target'] == 1)]

     feature_0  feature_1  ...  predicted_target  actual_target
101  -1.514298  -0.939463  ...                 0              1
902  -1.279317  -0.262747  ...                 0              1
221  -0.692609  -1.120047  ...                 0              1
209  -1.057059  -0.114641  ...                 0              1
382  -0.920439  -0.978500  ...                 0              1
959  -0.915856  -0.385673  ...                 0              1
995  -1.416963   1.202451  ...                 0              1
254  -0.802641   0.756488  ...                 0              1
845  -1.078296   0.652330  ...                 0              1

[9 rows x 12 columns]

In [21]:
# pass new input to the model
input = [[0.5]*10]
prediction = knn.predict(input)
print(f"Prediction for input {input}: {prediction}")

Prediction for input [[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]]: [0]

/Users/rahultiwari/Documents/ml_akila/ml-env/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

In [23]:
# lets check the shape x_train and y_train
print(f"x_train shape: {X.shape}, y_train shape: {y.shape}")

x_train shape: (1000, 10), y_train shape: (1000,)

In [25]:
y.value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [24]:
# oversampling the minority class using SMOTE
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)
print(f"Resampled X shape: {X_resampled.shape}, Resampled y shape: {y_resampled.shape}")

Resampled X shape: (1800, 10), Resampled y shape: (1800,)

In [27]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_resampled, y_resampled)   
y_pred = knn.predict(x_test)
# checking accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy after SMOTE: {accuracy:.2f}")

Accuracy after SMOTE: 0.98

In [ ]:
# undersampling the majority class using RandomUnderSampler
from imblearn.under_sampling import RandomUnderSampler
rus = RandomUnderSampler(random_state=42)
X_resampled, y_resampled = rus.fit_resample(X, y)

### Assignment

In [ ]:


# Read official documentation for KNN: https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html
# Do some experiment with different parameters of KNN and observe the changes in accuracy.( library one only : iris dataset)
# Try to create imbalanced dataset and see how KNN is performing.
# Try to use oversampling and undersampling techniques to balance the dataset and see how KNN is performing.
# Try to read ateast one blog for KNN (https://medium.com/swlh/k-nearest-neighbor-ca2593d7a3c4)

In [ ]:
# https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html#sklearn.neighbors.KNeighborsClassifier

In [ ]:
# Implement KNN from scratch : not using any library functions : load_iris()