In [1]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 30, 22, 35],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}

df = pd.DataFrame(data)
df.head()

      Name  Age         City
0    Alice   24     New York
1      Bob   30  Los Angeles
2  Charlie   22      Chicago
3    David   35      Houston

In [4]:
reviews = pd.read_csv('reviews.csv')
reviews.tail(2)

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
568452,568453,B004I613EE,A3IBEVCTXKNOH,"Kathy A. Welch ""katwel""",1,1,5,1331596800,Favorite Training and reward treat,These are the BEST treats for training and rew...
568453,568454,B001LR2CU2,A3LGQPJCZVL9UC,srfell17,0,0,5,1338422400,Great Honey,"I am very satisfied ,product is as advertised,..."

In [5]:
reviews.columns

Index(['Id', 'ProductId', 'UserId', 'ProfileName', 'HelpfulnessNumerator',
       'HelpfulnessDenominator', 'Score', 'Time', 'Summary', 'Text'],
      dtype='object')

In [6]:
reviews.shape

(568454, 10)

In [9]:
type(reviews)

pandas.core.frame.DataFrame

In [11]:
# slect col1 ,col 2 from reviews
reviews[['ProductId', 'UserId']].head(4)

    ProductId          UserId
0  B001E4KFG0  A3SGXH7AUHU8GW
1  B00813GRG4  A1D87F6ZCVE5NK
2  B000LQOCH0   ABXLMWJIXXAIN
3  B000UA0QIQ  A395BORC6FGVXV

In [13]:
reviews[reviews['Score'] < 3].shape

(82037, 10)

In [14]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 568454 entries, 0 to 568453
Data columns (total 10 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Id                      568454 non-null  int64
 1   ProductId               568454 non-null  object
 2   UserId                  568454 non-null  object
 3   ProfileName             568428 non-null  object
 4   HelpfulnessNumerator    568454 non-null  int64
 5   HelpfulnessDenominator  568454 non-null  int64
 6   Score                   568454 non-null  int64
 7   Time                    568454 non-null  int64
 8   Summary                 568427 non-null  object
 9   Text                    568454 non-null  object
dtypes: int64(5), object(5)
memory usage: 43.4+ MB

In [19]:
simple_data = {
    'product_category': ['Book', 'Book', 'Electronics', 'Clothing', 'Electronics'],
    'price': [12.99, 15.49, 199.99, 29.99, 99.99],
    'rating': [4.5, 4.0, 3.5, 5.0, 4.2]
}

df_simple = pd.DataFrame(simple_data)
df_simple.head()

  product_category   price  rating
0             Book   12.99     4.5
1             Book   15.49     4.0
2      Electronics  199.99     3.5
3         Clothing   29.99     5.0
4      Electronics   99.99     4.2

In [18]:
df_simple.product_category.value_counts()

product_category
Book           2
Electronics    2
Clothing       1
Name: count, dtype: int64

In [21]:
reviews['ProductId'].value_counts()

ProductId
B007JFMH8M    913
B0026RQTGE    632
B002QWHJOU    632
B002QWP89S    632
B002QWP8H0    632
             ...
B004DSPTTM      1
B008C9QWU8      1
B007O5A6BM      1
B003Q4TZ08      1
B001LR2CU2      1
Name: count, Length: 74258, dtype: int64

In [24]:
reviews[reviews['ProductId']=='B0026RQTGE'].shape

(632, 10)

In [33]:
df_simple.price.describe()

count      5.0000
mean      71.6900
std       80.0075
min       12.9900
25%       15.4900
50%       29.9900
75%       99.9900
max      199.9900
Name: price, dtype: float64

In [37]:
df_simple.describe(include='all')  # include all data types

       product_category     price    rating
count                 5    5.0000  5.000000
unique                3       NaN       NaN
top                Book       NaN       NaN
freq                  2       NaN       NaN
mean                NaN   71.6900  4.240000
std                 NaN   80.0075  0.559464
min                 NaN   12.9900  3.500000
25%                 NaN   15.4900  4.000000
50%                 NaN   29.9900  4.200000
75%                 NaN   99.9900  4.500000
max                 NaN  199.9900  5.000000

In [38]:
df_simple

  product_category   price  rating
0             Book   12.99     4.5
1             Book   15.49     4.0
2      Electronics  199.99     3.5
3         Clothing   29.99     5.0
4      Electronics   99.99     4.2

In [35]:
df_simple.product_category.describe()

count        5
unique       3
top       Book
freq         2
Name: product_category, dtype: object

In [44]:
df_simple.to_csv('simple_data.csv', index=False)
df_simple.to_excel('simple_data.xlsx', index=False)
df_simple.to_json('simple_data.json', index=False)
df_simple.to_html('simple_data.html', index=False)

In [45]:
url = (
    "https://raw.githubusercontent.com/pandas-dev"
    "/pandas/main/pandas/tests/io/data/csv/tips.csv"
)

tips = pd.read_csv(url)
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
tips['new_total_bill'] = tips['total_bill'] - 2

   total_bill   tip     sex smoker  day    time  size  new_total_bill
0       16.99  1.01  Female     No  Sun  Dinner     2           14.99
1       10.34  1.66    Male     No  Sun  Dinner     3            8.34
2       21.01  3.50    Male     No  Sun  Dinner     3           19.01
3       23.68  3.31    Male     No  Sun  Dinner     2           21.68
4       24.59  3.61  Female     No  Sun  Dinner     4           22.59

In [49]:
condition = ( tips['day'] == 'Sun') & (tips['new_total_bill'] > 20)
tips[condition]

     total_bill   tip     sex smoker  day    time  size  new_total_bill
3         23.68  3.31    Male     No  Sun  Dinner     2           21.68
4         24.59  3.61  Female     No  Sun  Dinner     4           22.59
5         25.29  4.71    Male     No  Sun  Dinner     4           23.29
7         26.88  3.12    Male     No  Sun  Dinner     4           24.88
11        35.26  5.00  Female     No  Sun  Dinner     4           33.26
44        30.40  5.60    Male     No  Sun  Dinner     4           28.40
46        22.23  5.00    Male     No  Sun  Dinner     2           20.23
47        32.40  6.00    Male     No  Sun  Dinner     4           30.40
48        28.55  2.05    Male     No  Sun  Dinner     3           26.55
52        34.81  5.20  Female     No  Sun  Dinner     4           32.81
54        25.56  4.34    Male     No  Sun  Dinner     4           23.56
112       38.07  4.00    Male     No  Sun  Dinner     3           36.07
113       23.95  2.55    Male     No  Sun  Dinner     2           21.95
114       25.71  4.00  Female     No  Sun  Dinner     3           23.71
116       29.93  5.07    Male     No  Sun  Dinner     4           27.93
153       24.55  2.00    Male     No  Sun  Dinner     4           22.55
155       29.85  5.14  Female     No  Sun  Dinner     5           27.85
156       48.17  5.00    Male     No  Sun  Dinner     6           46.17
157       25.00  3.75  Female     No  Sun  Dinner     4           23.00
165       24.52  3.48    Male     No  Sun  Dinner     3           22.52
167       31.71  4.50    Male     No  Sun  Dinner     4           29.71
173       31.85  3.18    Male    Yes  Sun  Dinner     2           29.85
175       32.90  3.11    Male    Yes  Sun  Dinner     2           30.90
179       34.63  3.55    Male    Yes  Sun  Dinner     2           32.63
180       34.65  3.68    Male    Yes  Sun  Dinner     4           32.65
181       23.33  5.65    Male    Yes  Sun  Dinner     2           21.33
182       45.35  3.50    Male    Yes  Sun  Dinner     3           43.35
183       23.17  6.50    Male    Yes  Sun  Dinner     4           21.17
184       40.55  3.00    Male    Yes  Sun  Dinner     2           38.55
187       30.46  2.00    Male    Yes  Sun  Dinner     5           28.46
189       23.10  4.00    Male    Yes  Sun  Dinner     3           21.10

In [50]:
def bucket_tip(tip):
    if tip < 10:
        return 'Low'
    return 'High'


tips['tip_bucket'] = tips['tip'].apply(bucket_tip)
tips.head()

,total_bill,tip,sex,smoker,day,time,size,new_total_bill,tip_bucket
0,16.99,1.01,Female,No,Sun,Dinner,2,14.99,Low
1,10.34,1.66,Male,No,Sun,Dinner,3,8.34,Low
2,21.01,3.50,Male,No,Sun,Dinner,3,19.01,Low
3,23.68,3.31,Male,No,Sun,Dinner,2,21.68,Low
4,24.59,3.61,Female,No,Sun,Dinner,4,22.59,Low

In [51]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   total_bill      244 non-null    float64
 1   tip             244 non-null    float64
 2   sex             244 non-null    object
 3   smoker          244 non-null    object
 4   day             244 non-null    object
 5   time            244 non-null    object
 6   size            244 non-null    int64
 7   new_total_bill  244 non-null    float64
 8   tip_bucket      244 non-null    object
dtypes: float64(3), int64(1), object(5)
memory usage: 17.3+ KB

In [56]:
tips.isnull().sum()

total_bill        0
tip               0
sex               0
smoker            0
day               0
time              0
size              0
new_total_bill    0
tip_bucket        0
dtype: int64

In [52]:
test_df = pd.DataFrame({
    'A': [1, 2, None, 4],
    'B': [None, 2, 3, 4],
    'C': [1, None, None, 4]
})
test_df.head()

     A    B    C
0  1.0  NaN  1.0
1  2.0  2.0  NaN
2  NaN  3.0  NaN
3  4.0  4.0  4.0

In [55]:
test_df.isnull().sum()

A    1
B    1
C    2
dtype: int64