In [1]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 30, 22, 35],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}

df = pd.DataFrame(data)
df.head()

      Name  Age         City
0    Alice   24     New York
1      Bob   30  Los Angeles
2  Charlie   22      Chicago
3    David   35      Houston

In [2]:
reviews = pd.read_csv('reviews.csv')
reviews.tail(2)

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
568452,568453,B004I613EE,A3IBEVCTXKNOH,"Kathy A. Welch ""katwel""",1,1,5,1331596800,Favorite Training and reward treat,These are the BEST treats for training and rew...
568453,568454,B001LR2CU2,A3LGQPJCZVL9UC,srfell17,0,0,5,1338422400,Great Honey,"I am very satisfied ,product is as advertised,..."

In [3]:
reviews.columns

Index(['Id', 'ProductId', 'UserId', 'ProfileName', 'HelpfulnessNumerator',
       'HelpfulnessDenominator', 'Score', 'Time', 'Summary', 'Text'],
      dtype='object')

In [4]:
reviews.shape

(568454, 10)

In [5]:
type(reviews)

pandas.core.frame.DataFrame

In [6]:
# slect col1 ,col 2 from reviews
reviews[['ProductId', 'UserId']].head(4)

    ProductId          UserId
0  B001E4KFG0  A3SGXH7AUHU8GW
1  B00813GRG4  A1D87F6ZCVE5NK
2  B000LQOCH0   ABXLMWJIXXAIN
3  B000UA0QIQ  A395BORC6FGVXV

In [7]:
reviews[reviews['Score'] < 3].shape

(82037, 10)

In [8]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 568454 entries, 0 to 568453
Data columns (total 10 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Id                      568454 non-null  int64
 1   ProductId               568454 non-null  object
 2   UserId                  568454 non-null  object
 3   ProfileName             568428 non-null  object
 4   HelpfulnessNumerator    568454 non-null  int64
 5   HelpfulnessDenominator  568454 non-null  int64
 6   Score                   568454 non-null  int64
 7   Time                    568454 non-null  int64
 8   Summary                 568427 non-null  object
 9   Text                    568454 non-null  object
dtypes: int64(5), object(5)
memory usage: 43.4+ MB

In [9]:
simple_data = {
    'product_category': ['Book', 'Book', 'Electronics', 'Clothing', 'Electronics'],
    'price': [12.99, 15.49, 199.99, 29.99, 99.99],
    'rating': [4.5, 4.0, 3.5, 5.0, 4.2]
}

df_simple = pd.DataFrame(simple_data)
df_simple.head()

  product_category   price  rating
0             Book   12.99     4.5
1             Book   15.49     4.0
2      Electronics  199.99     3.5
3         Clothing   29.99     5.0
4      Electronics   99.99     4.2

In [10]:
df_simple['discounted_price'] = df_simple['price'] * 0.9
df_simple.head()

  product_category   price  rating  discounted_price
0             Book   12.99     4.5            11.691
1             Book   15.49     4.0            13.941
2      Electronics  199.99     3.5           179.991
3         Clothing   29.99     5.0            26.991
4      Electronics   99.99     4.2            89.991

In [16]:
df_simple['pct_change_in_price']=df_simple['price'].pct_change()
df_simple.head()

  product_category   price  rating  discounted_price  pct_change_in_price
0             Book   12.99     4.5            11.691                  NaN
1             Book   15.49     4.0            13.941             0.192456
2      Electronics  199.99     3.5           179.991            11.910910
3         Clothing   29.99     5.0            26.991            -0.850043
4      Electronics   99.99     4.2            89.991             2.334111

In [11]:
df_simple.product_category.value_counts()

product_category
Book           2
Electronics    2
Clothing       1
Name: count, dtype: int64

In [12]:
reviews['ProductId'].value_counts()

ProductId
B007JFMH8M    913
B0026RQTGE    632
B002QWHJOU    632
B002QWP89S    632
B002QWP8H0    632
             ...
B004DSPTTM      1
B008C9QWU8      1
B007O5A6BM      1
B003Q4TZ08      1
B001LR2CU2      1
Name: count, Length: 74258, dtype: int64

In [24]:
reviews[reviews['ProductId']=='B0026RQTGE'].shape

(632, 10)

In [33]:
df_simple.price.describe()

count      5.0000
mean      71.6900
std       80.0075
min       12.9900
25%       15.4900
50%       29.9900
75%       99.9900
max      199.9900
Name: price, dtype: float64

In [15]:
df_simple.describe(include='all',percentiles=[0.30,0.75, 0.99])  # include all data types

       product_category     price    rating  discounted_price
count                 5    5.0000  5.000000           5.00000
unique                3       NaN       NaN               NaN
top                Book       NaN       NaN               NaN
freq                  2       NaN       NaN               NaN
mean                NaN   71.6900  4.240000          64.52100
std                 NaN   80.0075  0.559464          72.00675
min                 NaN   12.9900  3.500000          11.69100
30%                 NaN   18.3900  4.040000          16.55100
50%                 NaN   29.9900  4.200000          26.99100
75%                 NaN   99.9900  4.500000          89.99100
99%                 NaN  195.9900  4.980000         176.39100
max                 NaN  199.9900  5.000000         179.99100

In [38]:
df_simple

  product_category   price  rating
0             Book   12.99     4.5
1             Book   15.49     4.0
2      Electronics  199.99     3.5
3         Clothing   29.99     5.0
4      Electronics   99.99     4.2

In [35]:
df_simple.product_category.describe()

count        5
unique       3
top       Book
freq         2
Name: product_category, dtype: object

In [44]:
df_simple.to_csv('simple_data.csv', index=False)
df_simple.to_excel('simple_data.xlsx', index=False)
df_simple.to_json('simple_data.json', index=False)
df_simple.to_html('simple_data.html', index=False)

In [45]:
url = (
    "https://raw.githubusercontent.com/pandas-dev"
    "/pandas/main/pandas/tests/io/data/csv/tips.csv"
)

tips = pd.read_csv(url)
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
tips['new_total_bill'] = tips['total_bill'] - 2

   total_bill   tip     sex smoker  day    time  size  new_total_bill
0       16.99  1.01  Female     No  Sun  Dinner     2           14.99
1       10.34  1.66    Male     No  Sun  Dinner     3            8.34
2       21.01  3.50    Male     No  Sun  Dinner     3           19.01
3       23.68  3.31    Male     No  Sun  Dinner     2           21.68
4       24.59  3.61  Female     No  Sun  Dinner     4           22.59

In [49]:
condition = ( tips['day'] == 'Sun') & (tips['new_total_bill'] > 20)
tips[condition]

     total_bill   tip     sex smoker  day    time  size  new_total_bill
3         23.68  3.31    Male     No  Sun  Dinner     2           21.68
4         24.59  3.61  Female     No  Sun  Dinner     4           22.59
5         25.29  4.71    Male     No  Sun  Dinner     4           23.29
7         26.88  3.12    Male     No  Sun  Dinner     4           24.88
11        35.26  5.00  Female     No  Sun  Dinner     4           33.26
44        30.40  5.60    Male     No  Sun  Dinner     4           28.40
46        22.23  5.00    Male     No  Sun  Dinner     2           20.23
47        32.40  6.00    Male     No  Sun  Dinner     4           30.40
48        28.55  2.05    Male     No  Sun  Dinner     3           26.55
52        34.81  5.20  Female     No  Sun  Dinner     4           32.81
54        25.56  4.34    Male     No  Sun  Dinner     4           23.56
112       38.07  4.00    Male     No  Sun  Dinner     3           36.07
113       23.95  2.55    Male     No  Sun  Dinner     2           21.95
114       25.71  4.00  Female     No  Sun  Dinner     3           23.71
116       29.93  5.07    Male     No  Sun  Dinner     4           27.93
153       24.55  2.00    Male     No  Sun  Dinner     4           22.55
155       29.85  5.14  Female     No  Sun  Dinner     5           27.85
156       48.17  5.00    Male     No  Sun  Dinner     6           46.17
157       25.00  3.75  Female     No  Sun  Dinner     4           23.00
165       24.52  3.48    Male     No  Sun  Dinner     3           22.52
167       31.71  4.50    Male     No  Sun  Dinner     4           29.71
173       31.85  3.18    Male    Yes  Sun  Dinner     2           29.85
175       32.90  3.11    Male    Yes  Sun  Dinner     2           30.90
179       34.63  3.55    Male    Yes  Sun  Dinner     2           32.63
180       34.65  3.68    Male    Yes  Sun  Dinner     4           32.65
181       23.33  5.65    Male    Yes  Sun  Dinner     2           21.33
182       45.35  3.50    Male    Yes  Sun  Dinner     3           43.35
183       23.17  6.50    Male    Yes  Sun  Dinner     4           21.17
184       40.55  3.00    Male    Yes  Sun  Dinner     2           38.55
187       30.46  2.00    Male    Yes  Sun  Dinner     5           28.46
189       23.10  4.00    Male    Yes  Sun  Dinner     3           21.10

In [50]:
def bucket_tip(tip):
    if tip < 10:
        return 'Low'
    return 'High'


tips['tip_bucket'] = tips['tip'].apply(bucket_tip)
tips.head()

,total_bill,tip,sex,smoker,day,time,size,new_total_bill,tip_bucket
0,16.99,1.01,Female,No,Sun,Dinner,2,14.99,Low
1,10.34,1.66,Male,No,Sun,Dinner,3,8.34,Low
2,21.01,3.50,Male,No,Sun,Dinner,3,19.01,Low
3,23.68,3.31,Male,No,Sun,Dinner,2,21.68,Low
4,24.59,3.61,Female,No,Sun,Dinner,4,22.59,Low

In [51]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   total_bill      244 non-null    float64
 1   tip             244 non-null    float64
 2   sex             244 non-null    object
 3   smoker          244 non-null    object
 4   day             244 non-null    object
 5   time            244 non-null    object
 6   size            244 non-null    int64
 7   new_total_bill  244 non-null    float64
 8   tip_bucket      244 non-null    object
dtypes: float64(3), int64(1), object(5)
memory usage: 17.3+ KB

In [56]:
tips.isnull().sum()

total_bill        0
tip               0
sex               0
smoker            0
day               0
time              0
size              0
new_total_bill    0
tip_bucket        0
dtype: int64

In [52]:
test_df = pd.DataFrame({
    'A': [1, 2, None, 4],
    'B': [None, 2, 3, 4],
    'C': [1, None, None, 4]
})
test_df.head()

     A    B    C
0  1.0  NaN  1.0
1  2.0  2.0  NaN
2  NaN  3.0  NaN
3  4.0  4.0  4.0

In [55]:
test_df.isnull().sum()

A    1
B    1
C    2
dtype: int64

In [ ]:
# https://pandas.pydata.org/docs/getting_started/comparison/comparison_with_spreadsheets.html#compare-with-spreadsheets

In [3]:
car_df = pd.read_csv('car_price_dataset_medium.csv')

In [10]:
car_df.rename(columns={'Price_USD': 'Price'}, inplace=True)
car_df.head()

,Car_ID,Brand,Model_Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Engine_CC,Max_Power_bhp,Mileage_kmpl,Seats,Price
0,1,Audi,2005,197018,Diesel,Manual,First,4046,223.6,29.61,6,119611.94
1,2,BMW,2019,43467,Hybrid,Automatic,First,3731,248.4,21.66,5,90842.46
2,3,Kia,2012,153697,Hybrid,Automatic,Third,4925,465.5,12.14,6,78432.24
3,4,Mercedes,2015,38893,Petrol,Automatic,Second,3771,229.7,19.65,6,44568.89
4,5,Audi,2016,81329,Hybrid,Automatic,First,2817,573.2,7.74,5,8751.82

In [ ]:
# car_df.head()

# car_df.head()
# car_df.Brand.value_counts()
car_df.groupby('Brand').agg({
    'Price': ['mean', 'min', 'max'],
})

                   Price                     Kilometers_Driven
                    mean      min        max              mean    min     max
Brand
Audi        62351.394043  3353.44  119611.94     103320.542553  11304  197699
BMW         54154.605532  3048.00  119074.79     103444.202128   5781  199812
Ford        59953.021364  5446.41  119533.50     102223.272727   5207  199718
Honda       57226.331687  3435.20  118306.32     101564.807229   8191  199018
Hyundai     58818.596354  5572.42  119200.16     107235.135417   7659  197660
Kia         56090.171700  4248.40  117194.36     105549.220000   5587  197404
Mercedes    64344.239907  3092.37  119331.69     103746.560748   5163  199442
Nissan      64089.937473  3274.65  119508.88      92807.076923   7336  198718
Toyota      58964.422288  4522.19  118626.67     103632.771186   5155  195546
Volkswagen  55987.339720  3028.42  119485.69     108993.093458   8754  199509

In [18]:
report = car_df.groupby(['Brand','Fuel_Type']).agg({
    'Price': ['mean', 'min', 'max'],
    'Kilometers_Driven': ['mean', 'min', 'max']

})

report.reset_index()

         Brand Fuel_Type         Price                      Kilometers_Driven  \
                                  mean       min        max              mean
0         Audi    Diesel  53277.218333   6647.46  119611.94     101066.111111
1         Audi  Electric  66219.721786   7718.63  117780.45     108908.928571
2         Audi    Hybrid  51630.635000   4853.05  108995.44      98900.000000
3         Audi    Petrol  70617.915667   3353.44  118402.94     102109.700000
4          BMW    Diesel  48959.442000   6623.56  119074.79     100845.360000
5          BMW  Electric  54149.664737   3794.22  107571.58     114889.842105
6          BMW    Hybrid  58269.813529   3048.00  117970.33      98785.941176
7          BMW    Petrol  55973.224545   4081.27  113459.09     101222.818182
8         Ford    Diesel  68400.834800  14579.33  115351.16     100745.720000
9         Ford  Electric  61466.326000   9612.34  117485.20     107817.866667
10        Ford    Hybrid  58267.564483   5446.41  119533.50      84362.206897
11        Ford    Petrol  51963.935769   8165.03  102004.68     117110.653846
12       Honda    Diesel  52425.412857   3435.20  113093.00      94958.142857
13       Honda  Electric  53512.097143   3988.83  105829.09     116963.500000
14       Honda    Hybrid  71787.621429  32507.68  107608.69     103744.714286
15       Honda    Petrol  56580.663333   5597.73  118306.32      99301.333333
16     Hyundai    Diesel  61928.550000   9473.89  113992.53     115716.000000
17     Hyundai  Electric  58432.903462   8237.90  117735.84      97195.884615
18     Hyundai    Hybrid  59517.330690   7071.51  117136.70     114020.689655
19     Hyundai    Petrol  55369.341429   5572.42  119200.16     102217.142857
20         Kia    Diesel  61106.624545   4248.40  114842.50     104005.954545
21         Kia  Electric  49418.496296   4412.18  103893.19     108452.962963
22         Kia    Hybrid  58292.231538   5853.75  117194.36     106411.576923
23         Kia    Petrol  56590.960400   5589.73  113535.76     102874.400000
24    Mercedes    Diesel  57420.207241   9089.36  114194.43      99399.655172
25    Mercedes  Electric  63856.970000   7166.62  119331.69      83433.956522
26    Mercedes    Hybrid  62423.763571   3092.37  115230.55     121419.428571
27    Mercedes    Petrol  74187.850741   4754.82  116927.88     107391.370370
28      Nissan    Diesel  54568.085000   6606.48  108656.93     118871.416667
29      Nissan  Electric  57270.161923   4595.86  114947.32      82736.076923
30      Nissan    Hybrid  73774.305862   4076.51  112611.85     105457.000000
31      Nissan    Petrol  64537.008750   3274.65  119508.88      75399.833333
32      Toyota    Diesel  58689.083182   4522.19  116264.48     102730.000000
33      Toyota  Electric  67885.625161  10605.09  116857.93     108034.258065
34      Toyota    Hybrid  53863.721765   5109.75  118626.67     107561.852941
35      Toyota    Petrol  55832.938065   4738.17  108473.84      95562.645161
36  Volkswagen    Diesel  59495.049583   6412.97  116750.88     131835.333333
37  Volkswagen  Electric  61603.096071   4348.54  116846.31     106374.500000
38  Volkswagen    Hybrid  57499.526429   5633.01  117201.16     105053.821429
39  Volkswagen    Petrol  45477.434444   3028.42  119485.69      95489.629630


      min     max
0   11304  197018
1   25074  197699
2   12099  195736
3   14686  189816
4    6283  195135
5   23313  199812
6   19849  170575
7    5781  198783
8    5207  192598
9   21456  199718
10  10906  196703
11  30169  195747
12  11910  190378
13  11548  168856
14   8191  197402
15  10901  199018
16  23099  190165
17   9135  197660
18  10075  194351
19   7659  184402
20   5587  197404
21  15749  194784
22   9895  186801
23  10782  177395
24   5163  190413
25  10469  199442
26  10347  193978
27  17109  185217
28   8471  197035
29  11721  193785
30   7336  195237
31  11710  198718
32  13706  191186
33   8631  184830
34  23708  195546
35   5155  191368
36  18428  199509
37  22073  197630
38   8754  192921
39  14283  183313